version: '3.1'

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: client1
      POSTGRES_PASSWORD: client1
      POSTGRES_DB: EstHotelPro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U client1 -d EstHotelPro" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8086:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/EstHotelPro
      SPRING_DATASOURCE_USERNAME: client1
      SPRING_DATASOURCE_PASSWORD: client1
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_FLYWAY_LOCATIONS: db/migration
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
